### ISSUE TITLE
"Send" button is greyed out

### ISSUE THREAD

**Issue by taoeffect** [johansten/stargazer#26]
Was able to receive XLM but can't send. Using macOS with version 1.5.3. Help appreciated.

**Comment by johansten** [comment]
What's your account balance? Do you have any trust lines set up?

**Comment by taoeffect** [comment]
My account balance is non-zero. I do not have any trust lines set up.

**Comment by legleux** [comment]
This is happening to me also. It seems to be greyed out for arbitrary values.
Not being able to export or view the private key is pretty terrible also.

**Comment by Fonbaron11** [comment]
Good day! I have the same problem, did anyone solved it?

**Comment by kfiresmith** [comment]
I'm going to close this issue out due to old age.  If any participants are still having problems please do feel free to ping this ticket, create a new one, or find my on Slack '[stellar-public](https://stellar-public.slack.com)' at KodiakFi.

**Comment by SavageNH** [comment]
I'm having this exact problem now. Wallet balance is 105+ lumens. "Send" button is greyed out and does nothing when clicked. Stargazer version 1.5.4

**Comment by johansten** [comment]
I've only ever managed to replicate this issue *one* time, and it turned out to be because of some discrepancy between my development build (where is always works), and the installed app (where it turned out it didn't). Somehow, it works now in the installed app.

@SavageNH 1.6.0 is coming out within a day, try it again and see if it works better.

**Comment by johansten** [comment]
Got confirmation on twitter that 1.6.0 solved it
https://twitter.com/MAD_4_CRYPTO/status/987517626237771776
